<a href="https://colab.research.google.com/github/rtajeong/M3_new/blob/main/M3_lab34a_scikit_learn_object.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Scikit-Learn API
- to show how scikit-learn objects are made
- all objects share a consistent and simple interface:
   - fit(): estimators
   - transform(): transformers
   - fit_transform(): fit() + transform()
   - predict(): prediction


In [ ]:
import numpy as np
from scipy import sparse
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.utils.validation import check_array, check_is_fitted
from sklearn.utils.sparsefuncs import inplace_column_scale, mean_variance_axis

In [ ]:
def _mean_and_std(X, axis=0):
   
    X = np.asarray(X)
    mean_ = X.mean(axis)
    std_ = X.std(axis)

    return mean_, std_

In [ ]:
data = np.array([[1,2,3],[4,5,6]]); data

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
_mean_and_std(data, 0), _mean_and_std(data, 1)

((array([2.5, 3.5, 4.5]), array([1.5, 1.5, 1.5])),
 (array([2., 5.]), array([0.81649658, 0.81649658])))

In [ ]:
class my_StandardScaler():

    def __init__(self):
        self.mean_, self.std_ = 0., 0.
        
    def fit(self, X, y=None):
        X = X.astype(np.float32)
        self.mean_, self.std_ = _mean_and_std(X, axis=0)
        return self

    def transform(self, X, y=None):
        X = X.astype(np.float32)
        X -= self.mean_
        X /= self.std_
        return X

    def inverse_transform(self, X):
        X = X.astype(np.float32)
        X *= self.std_
        X += self.mean_
        return X

In [ ]:
X = np.array([1,2,3,4,5,6,7,8,9,10])
sc = my_StandardScaler()

In [ ]:
# dir(sc)

In [ ]:
sc.fit(X)

In [ ]:
sc.mean_, sc.std_

(5.5, 2.8722813)

In [ ]:
X_sc = sc.transform(X); X_sc

array([-1.5666989 , -1.2185436 , -0.87038827, -0.52223295, -0.17407766,
        0.17407766,  0.52223295,  0.87038827,  1.2185436 ,  1.5666989 ],
      dtype=float32)

In [ ]:
sc.inverse_transform(X_sc)

array([ 1.       ,  1.9999998,  3.       ,  4.       ,  5.       ,
        6.       ,  7.       ,  8.       ,  9.       , 10.       ],
      dtype=float32)